name: build games

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - games/**
concurrency:
  group: games-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "games_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - source-sourcemod
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: ./games
          file: ./games/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/software-noob/pterodactyl-images:games_${{ matrix.tag }}
